# .github/labeler.yml
# Translates PR file changes into automated labels

frontend:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.tsx'
      - '**/*.ts'
      - '**/*.jsx'
      - '**/*.js'
      - '**/*.css'

docs:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

config:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'vite.config.ts'
      - '.github/**/*'
